openapi: 3.0.0
servers:
  - description: APIHub API Auto Mocking court-hearing-judges
    url: https://virtserver.swaggerhub.com/HMCTS-DTS/api-cp-piloting-pathfinder/0.0.0

info:
  title: Piloting API
  description: A simple API to demonstrate best practice capabilities
  version: 0.0.0
  contact:
    email: no-reply@hmcts.com
  license:
    name: MIT
    url: 'https://opensource.org/licenses/MIT'

tags:
  - name: Auth
    description: Authentication and authorisation details
paths:
  /example/auth/{id}:
    get:
      description: Dummy retrieve details of a authorised user
      operationId: getAuthById
      tags:
        - Auth
      parameters:
        - in: path
          name: id
          required: true
          description: Unique id
          schema:
            type: string
      responses:
        '200':
          description: auth details found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Auth"
        '400':
          description: bad input parameter
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

components:
  schemas:
    Auth:
      type: object
      properties:
        userName:
          type: string
          description: Authorised users name

    ErrorResponse:
      type: object
      properties:
        error:
          type: string
          description: Machine-readable error code
        message:
          type: string
          description: Human-readable error message
        details:
          type: object
          additionalProperties: true
          description: Additional error context
        timestamp:
          type: string
          format: date-time
        traceId:
          type: string
          description: Unique identifier for error tracing
