name: Publish OpenAPI Spec to APIHub

on:
  workflow_call:
    secrets:
      SWAGGERHUB_API_KEY:
        required: true
    inputs:
      upload_artifact_name:
        required: true
        type: string
      apihub_owner:
        required: true
        type: string
      api_name:
        required: true
        type: string
      api_version:
        required: true
        type: string
      is_release:
        required: false
        type: boolean
        default: false

jobs:
  Push-API-to-APIHub:
    runs-on: ubuntu-latest
    steps:
      - uses: hmcts/publish-openapi-spec-to-apihub@temp
        with:
          swaggerhub_api_key: ${{ secrets.SWAGGERHUB_API_KEY }}
          upload_artifact_name: ${{ inputs.upload_artifact_name }}
          apihub_owner: ${{ inputs.apihub_owner}}
          api_name: ${{ inputs.api_name}}
          api_version: ${{ inputs.api_version}}
          is_release: ${{ inputs.is_release}}
